### ISSUE TITLE
Enhance simple usage example (based on user confusion)

### ISSUE THREAD

**Issue by mypark** [ToothlessGear/node-gcm#70]
So my GCM push message works if I use this test link

http://www.androidbegin.com/tutorial/gcm.html

And here's the response I get from that test link:

    { "multicast_id":7724943165862866717,
      "success":1,
      "failure":0,
      "canonical_ids":0,
      "results":[{"message_id":"0:1418649384921891% 7fd2b314f9fd7ecd"}]}

However if I push using my own service using node push service using the node-gcm lib, I get a success message on the server but no msg makes it to the client

Here's the success message from the node service:

    { multicast_id: 5130374164465991000,
      success: 1,
      failure: 0,
      canonical_ids: 0,
      results: [ { message_id: '0:1418649238305331%7fd2b3145bca2e79' } ] }

How come I'm getting a success message on the server, but no push is received on the client when using the node-gcm library based service.  Is there some sort of ip configuration that I need to do, or some sort of certificate?  I've used the same google api server key which is open to all ips on both examples.

I'm using the boiler plate code:

    var gcm = require('node-gcm');
    
    // create a message with default values
    var message = new gcm.Message();
    
    // or with object values
    var message = new gcm.Message({
        collapseKey: 'demo',
        delayWhileIdle: true,
        timeToLive: 3,
        data: {
            key1: 'message1',
            key2: 'message2'
        }
    });
    
    var sender = new gcm.Sender('insert Google Server API Key here');
    var registrationIds = ['regId1'];
 
    /**
     * Params: message-literal, registrationIds-array, No. of retries, callback-function
     **/
    sender.send(message, registrationIds, 4, function (err, result) {
        console.log(result);
    });

**Comment by Nonemoticoner** [comment]
I have the same problem. It is possible to achieve a succesful push with PHP code in GCM.php file on this website: http://www.androidhive.info/2012/10/android-push-notifications-using-google-cloud-messaging-gcm-php-and-mysql/
Although, using PHP is not what I'm aiming to, so hopefully we could figure that out, together.

**Comment by Nonemoticoner** [comment]
Okay, I have found the solution for my case. Hopefully, it's useful to you @mypark as well:

```javascript
var sender = new gcm.Sender(googleApiKey);
var message = new gcm.Message();
message.addData('key1','testdarinodegcm');
message.delay_while_idle = 1;
var registrationIds = [];
registrationIds.push('APA91bHCzBP6wEfExCZlSXgf0wuOC6QEWJ-7MVFl3hgaW3Jv8FslsofGJ-      qgdliyS8zjwy_W7zPaKsEZx6kbeuWdoAAexawKl1Qd6GEGV_v844n1LMRaTsWeiwI9iaLGKKq_R3scY_wuRG8uG2SZ5X9q0J67Ko3gcw');
sender.send(message, registrationIds, 4, function (err, result) {
console.log(result);
});
```

http://stackoverflow.com/questions/16410027/cant-receive-data-from-node-gcm
Firstly, it seemed stupid, but funnily it helped. I think devs should take a closer look on differences between making pushes in a usual way and that one provided by khurrum on StackOverFlow.

**Comment by hypesystem** [comment]
Hello Nonemoticoner! You are perfectly right. Somehow i didn't see this when I first read through the issue. It's a case of simple misunderstanding: the "boilerplate code" is not supposed to be a runnable example, but showing all the different ways the methods can be used. I see how this may cause confusion. Let's fix that right up!

**Comment by hypesystem** [comment]
How would you have reacted if this was the top of the **Usage** section?

---

## Usage

To send a message you need to know the Registration IDs of your recipients, and have created an API key for GCM. Here is a simple example of how to send your first notification:

```js
var gcm = require("node-gcm");

// Replace these Registration IDs with actual Registration IDs
var registrationIds = [
  "FIRST_RECIPIENT'S_REGISTRATION_ID",
  "SECOND_RECIPIENT'S_REGISTRATION_ID"
];

var message = new gcm.Message({
  data: {
    testMessage: "This message is transmitted to the recipient device."
  }
});

// Replace this key with your GCM API key
var sender = new gcm.Sender("YOUR API KEY");

// Actually send off the message
sender.send(message, registrationIds, function(err, result) {
  // Handle response from server
  if (err) console.error("Something went wrong!", err);
  else     console.log("Succesfully sent message. Got result", result);
});
```

The library provides quite a few ways to customize the notifications and the way they are sent. The following is a quick overview:

```js
// Create a message
// ... with default values
var message = new gcm.Message();
```

... (section continues)

**Comment by Nonemoticoner** [comment]
@hypesystem I believe the Usage is good enough. I've just talked to my friend with whom I'm working on GCM and it's been just Android application fault. I didn't have any flaws in my Node server-side scripting. I've just ran the previous piece of code I made and it worked for the newer Android app version.

@mypark It's most probably the device fault that push notification doesn't show.

**Comment by hypesystem** [comment]
Ah. Well that's a relief. Anyway, I think it is clear from @mypark's example that the usage section *can* lead to confusion.

He has the following lines:

```js
// create a message with default values
var message = new gcm.Message();

// or with object values
var message = new gcm.Message({
  // ... (removed for bevity)
});
```

Here, he instantiates who messages as `var message`. This is syntactically broken in Javascript. And we do this in our Usage section. That, I think, is cause for reflection and potentially a revision.

I am going to keep thinking about how to best do this, but your input is valued :) Best of luck with your project.

**Comment by hypesystem** [comment]
Fixed by #110

**Comment by Shivendra30** [comment]
I used the same code as provided by @Nonemoticoner above:

```
var sender = new gcm.Sender(googleApiKey);
var message = new gcm.Message();
message.addData('key1','testdarinodegcm');
message.delay_while_idle = 1;
var registrationIds = [];
registrationIds.push(reg_id);
sender.send(message, registrationIds, 4, function (err, result) {
console.log(result);
});
```

However, my app client app (react native Android) is still crashing when the notification is sent from the server.

From the server, I get the following success message:
```
{ multicast_id: 5346493375647405000,
  success: 1,
  failure: 0,
  canonical_ids: 0,
  results: [ { message_id: '0:1544767360018299%a0be8ac5f9fd7ecd' } ] }

```

What could be the possible issue now?

**Comment by hypesystem** [comment]
@Shivendra30 you would have to look at your client side (Android app) code to figure out what goes wrong on that end. FCM is telling you that delivery was a success, so the error must be in the app.

For this kind of problem, try [StackOverflow](https://stackoverflow.com/) or [AskQuestions.Tech](https://www.askquestions.tech/) for help debugging. It's unfortunately outside of the scope of this library.

**Comment by RenanRosa** [comment]
In my case, I rebooted the test device and now the notification works.
